version: '3'
services:
  client:
    ports:
      - "3000:3000"  
    volumes:
      - /app/node_modules
      - .:/app
    build:
      dockerfile: Dockerfile.dev
    environment:
       - CHOKIDAR_USEPOLLING=true  