FROM node:18.13.0-alpine as build
WORKDIR /app
COPY . /app
RUN echo ls -ltra
RUN echo $(pwd)
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install
CMD npm start --host 0.0.0.0 --port 3000 --disableHostCheck true